# Generated by Django 2.0.5 on 2018-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='', max_length=20, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='电话'),
        ),
    ]
