# Generated by Django 2.0.5 on 2018-06-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180604_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tag',
        ),
    ]
