# Generated by Django 2.0.5 on 2018-06-11 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0016_auto_20180612_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.WorkOrder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '跟进情况',
                'verbose_name_plural': '跟进情况',
            },
        ),
    ]
