# Generated by Django 2.0.5 on 2018-06-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180617_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='media/img/default.jpg', null=True, upload_to='img/%Y%M', verbose_name='头像'),
        ),
    ]
