# Generated by Django 2.0.5 on 2018-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
    ]
