# Generated by Django 2.0.5 on 2018-06-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180602_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='followup_notes',
            field=models.TextField(blank=True, null=True, verbose_name='更新类容'),
        ),
    ]
