# Generated by Django 2.0.5 on 2018-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180602_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='order/resource/%Y/%m', verbose_name='附件'),
        ),
    ]
