# Generated by Django 2.0.5 on 2018-06-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_workorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='em_id',
            field=models.CharField(default='', max_length=20, verbose_name='员工号'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='电话'),
        ),
    ]
