# Generated by Django 2.0.5 on 2018-06-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20180605_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='em_id',
            new_name='employee_id',
        ),
    ]
