# Generated by Django 2.0.6 on 2018-06-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20180609_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_notes', models.TextField(blank=True, null=True, verbose_name='更新类容')),
                ('resolution_notes', models.TextField(verbose_name='解决方案')),
                ('resolution_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Resolution', verbose_name='解决类型')),
            ],
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='followup_notes',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='resolution_code',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='resolution_notes',
        ),
    ]
