# Generated by Django 2.0.6 on 2018-06-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20180609_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='电话'),
        ),
    ]
