# Generated by Django 2.0.6 on 2018-06-09 09:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20180609_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=30, verbose_name='优先级')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '优先级',
                'verbose_name_plural': '优先级',
            },
        ),
        migrations.CreateModel(
            name='Statue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '状态',
                'verbose_name_plural': '状态',
            },
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='指派给'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.Category', verbose_name='故障类型'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.Priority', verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='statue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.Statue', verbose_name='状态'),
        ),
    ]
