# Generated by Django 2.0.5 on 2018-06-12 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20180612_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='关闭时间'),
        ),
    ]
